const data = {
    cities: [
        "Ahmadpur East",
        "Ahmed Nager Chatha",
        "Ali Khan Abad",
        "Alipur",
        "Arifwala",
        "Attock",
        "Bhera",
        "Bhalwal",
        "Bahawalnagar",
        "Bahawalpur",
        "Bhakkar",
        "Burewala",
        "Chenab Nagar",
        "Chillianwala",
        "Choa Saidanshah",
        "Chakwal",
        "Chak Jhumra",
        "Chichawatni",
        "Chiniot",
        "Chishtian",
        "Chunian",
        "Dajkot",
        "Daska",
        "Davispur",
        "Darya Khan",
        "Dera Ghazi Khan",
        "Dhaular",
        "Dina",
        "Dinga",
        "Dhudial Chakwal",
        "Dipalpur",
        "Faisalabad",
        "Fateh Jang",
        "Ghakhar Mandi",
        "Gojra",
        "Gujranwala",
        "Gujrat",
        "Gujar Khan",
        "Harappa",
        "Hafizabad",
        "Haroonabad",
        "Hasilpur",
        "Haveli Lakha",
        "Jalalpur Jattan",
        "Jampur",
        "Jaranwala",
        "Jhang",
        "Jhelum",
        "Kallar Syedan",
        "Kalabagh",
        "Karor Lal Esan",
        "Kasur",
        "Kamalia",
        "Kāmoke",
        "Khanewal",
        "Khanpur",
        "Khanqah Sharif",
        "Kharian",
        "Khushab",
        "Kot Adu",
        "Jauharabad",
        "Lahore",
        "Islamabad",
        "Lalamusa",
        "Layyah",
        "Lawa Chakwal",
        "Liaquat Pur",
        "Lodhran",
        "Malakwal",
        "Mamoori",
        "Mailsi",
        "Mandi Bahauddin",
        "Mian Channu",
        "Mianwali",
        "Miani",
        "Multan",
        "Murree",
        "Muridke",
        "Mianwali Bangla",
        "Muzaffargarh",
        "Narowal",
        "Nankana Sahib",
        "Okara",
        "Renala Khurd",
        "Pakpattan",
        "Pattoki",
        "Pindi Bhattian",
        "Pind Dadan Khan",
        "Pir Mahal",
        "Qaimpur",
        "Qila Didar Singh",
        "Raiwind",
        "Rajanpur",
        "Rahim Yar Khan",
        "Rawalpindi",
        "Sadiqabad",
        "Sagri",
        "Sahiwal",
        "Sambrial",
        "Samundri",
        "Sangla Hill",
        "Sarai Alamgir",
        "Sargodha",
        "Shakargarh",
        "Sheikhupura",
        "Shujaabad",
        "Sialkot",
        "Sohawa",
        "Soianwala",
        "Siranwali",
        "Tandlianwala",
        "Talagang",
        "Taxila",
        "Toba Tek Singh",
        "Vehari",
        "Wah Cantonment",
        "Wazirabad",
        "Yazman",
        "Zafarwal",
    ],
    industries: [
        "Advertising",
        "Agriculture",
        "Apparel & Accessories",
        "Art",
        "Automotive",
        "Baby Care",
        "Baking",
        "Beauty",
        "Bed & Bath",
        "Books",
        "Business",
        "Children",
        "Coupons",
        "Cryptocurrency",
        "Culinary",
        "Dating",
        "Design",
        "Digital Media",
        "Electronic Cigarettes",
        "Electronics",
        "Employment",
        "Entertainment",
        "Equipment",
        "Finance",
        "Food & Beverages",
        "Gaming",
        "Health & Fitness",
        "Hobbies",
        "Home",
        "Hospitality",
        "Information",
        "Jewelry",
        "Kitchenware",
        "Legal",
        "Lifestyle",
        "Medical",
        "Music",
        "News & Education",
        "Occasions & Gifts",
        "Office Supply",
        "Outdoors",
        "Parenting",
        "Personal Care",
        "Pet Care",
        "Quizzes",
        "Real Estate",
        "Religion & Spirituality",
        "Retail & Wholesale",
        "Romance",
        "Science",
        "SEO",
        "Social Media",
        "Sports",
        "Supplements",
        "Survival & Security",
        "Technology",
        "Tobacco Accessories",
        "Travel",
    ],
};

module.exports = function getData() {
    return data;
};
