const data = {
    countries: [
        { isoCode: "US", name: "United States of America" },
        { isoCode: "AT", name: "Austria" },
        { isoCode: "BE", name: "Belgium" },
        { isoCode: "BG", name: "Bulgaria" },
        { isoCode: "HR", name: "Croatia" },
        { isoCode: "CY", name: "Cyprus" },
        { isoCode: "CZ", name: "Czech Republic" },
        { isoCode: "DK", name: "Denmark" },
        { isoCode: "EE", name: "Estonia" },
        { isoCode: "FI", name: "Finland" },
        { isoCode: "FR", name: "France" },
        { isoCode: "DE", name: "Germany" },
        { isoCode: "GR", name: "Greece" },
        { isoCode: "HU", name: "Hungary" },
        { isoCode: "IE", name: "Ireland, Republic of (EIRE)" },
        { isoCode: "IT", name: "Italy" },
        { isoCode: "LV", name: "Latvia" },
        { isoCode: "LT", name: "Lithuania" },
        { isoCode: "LU", name: "Luxembourg" },
        { isoCode: "MT", name: "Malta" },
        { isoCode: "NL", name: "Netherlands" },
        { isoCode: "PL", name: "Poland" },
        { isoCode: "PT", name: "Portugal" },
        { isoCode: "RO", name: "Romania" },
        { isoCode: "SK", name: "Slovakia" },
        { isoCode: "SI", name: "Slovenia" },
        { isoCode: "ES", name: "Spain" },
        { isoCode: "SE", name: "Sweden" },
        { isoCode: "GB", name: "United Kingdom (Great Britain)" },
        { isoCode: "GF", name: "French Guiana" },
        { isoCode: "GP", name: "Guadeloupe" },
        { isoCode: "MQ", name: "Martinique" },
        { isoCode: "ME", name: "Montenegro" },
        { isoCode: "YT", name: "Mayotte" },
        { isoCode: "RE", name: "Réunion" },
        { isoCode: "MF", name: "Saint Martin" },
        { isoCode: "GI", name: "Gibraltar" },
        { isoCode: "AX", name: "Åland Islands" },
        { isoCode: "PM", name: "Saint Pierre and Miquelon" },
        { isoCode: "GL", name: "Greenland" },
        { isoCode: "BL", name: "Saint Bartelemey" },
        { isoCode: "SX", name: "Sint Maarten" },
        { isoCode: "AW", name: "Aruba" },
        { isoCode: "CW", name: "Curacao" },
        { isoCode: "WF", name: "Wallis and Futuna" },
        { isoCode: "PF", name: "French Polynesia" },
        { isoCode: "NC", name: "New Caledonia" },
        { isoCode: "TF", name: "French Southern Territories" },
        { isoCode: "AI", name: "Anguilla" },
        { isoCode: "BM", name: "Bermuda" },
        { isoCode: "IO", name: "British Indian Ocean Territory" },
        { isoCode: "VG", name: "Virgin Islands, British" },
        { isoCode: "KY", name: "Cayman Islands" },
        { isoCode: "FK", name: "Falkland Islands (Malvinas)" },
        { isoCode: "MS", name: "Montserrat" },
        { isoCode: "PN", name: "Pitcairn" },
        { isoCode: "SH", name: "Saint Helena" },
        { isoCode: "GS", name: "South Georgia and the South Sandwich Islands" },
        { isoCode: "TC", name: "Turks and Caicos Islands" },
        { isoCode: "AD", name: "Andorra" },
        { isoCode: "LI", name: "Liechtenstein" },
        { isoCode: "MC", name: "Monaco" },
        { isoCode: "SM", name: "San Marino" },
        { isoCode: "VA", name: "Vatican City" },
        { isoCode: "JE", name: "Jersey" },
        { isoCode: "GG", name: "Guernsey" },
        { isoCode: "GI", name: "Gibraltar" },
    ],
    cities: [
        "Ahmadpur East",
        "Ahmed Nager Chatha",
        "Ali Khan Abad",
        "Alipur",
        "Arifwala",
        "Attock",
        "Bhera",
        "Bhalwal",
        "Bahawalnagar",
        "Bahawalpur",
        "Bhakkar",
        "Burewala",
        "Chenab Nagar",
        "Chillianwala",
        "Choa Saidanshah",
        "Chakwal",
        "Chak Jhumra",
        "Chichawatni",
        "Chiniot",
        "Chishtian",
        "Chunian",
        "Dajkot",
        "Daska",
        "Davispur",
        "Darya Khan",
        "Dera Ghazi Khan",
        "Dhaular",
        "Dina",
        "Dinga",
        "Dhudial Chakwal",
        "Dipalpur",
        "Faisalabad",
        "Fateh Jang",
        "Ghakhar Mandi",
        "Gojra",
        "Gujranwala",
        "Gujrat",
        "Gujar Khan",
        "Harappa",
        "Hafizabad",
        "Haroonabad",
        "Hasilpur",
        "Haveli Lakha",
        "Islamabad",
        "Jalalpur Jattan",
        "Jampur",
        "Jaranwala",
        "Jhang",
        "Jhelum",
        "Jauharabad",
        "Kallar Syedan",
        "Kalabagh",
        "Karor Lal Esan",
        "Karachi",
        "Kasur",
        "Kamalia",
        "Kāmoke",
        "Khanewal",
        "Khanpur",
        "Khanqah Sharif",
        "Kharian",
        "Khushab",
        "Kot Adu",
        "Lahore",
        "Lalamusa",
        "Layyah",
        "Lawa Chakwal",
        "Liaquat Pur",
        "Lodhran",
        "Malakwal",
        "Mamoori",
        "Mailsi",
        "Mandi Bahauddin",
        "Mian Channu",
        "Mianwali",
        "Miani",
        "Multan",
        "Murree",
        "Muridke",
        "Mianwali Bangla",
        "Muzaffargarh",
        "Narowal",
        "Nankana Sahib",
        "Okara",
        "Pakpattan",
        "Pattoki",
        "Pindi Bhattian",
        "Pind Dadan Khan",
        "Pir Mahal",
        "Qaimpur",
        "Qila Didar Singh",
        "Raiwind",
        "Rajanpur",
        "Rahim Yar Khan",
        "Rawalpindi",
        "Renala Khurd",
        "Sadiqabad",
        "Sagri",
        "Sahiwal",
        "Sambrial",
        "Samundri",
        "Sangla Hill",
        "Sarai Alamgir",
        "Sargodha",
        "Shakargarh",
        "Sheikhupura",
        "Shujaabad",
        "Sialkot",
        "Sohawa",
        "Soianwala",
        "Siranwali",
        "Tandlianwala",
        "Talagang",
        "Taxila",
        "Toba Tek Singh",
        "Vehari",
        "Wah Cantonment",
        "Wazirabad",
        "Yazman",
        "Zafarwal",
    ],
    industries: [
        "Advertising",
        "Agriculture",
        "Apparel & Accessories",
        "Art",
        "Automotive",
        "Baby Care",
        "Baking",
        "Beauty",
        "Bed & Bath",
        "Books",
        "Business",
        "Children",
        "Coupons",
        "Cryptocurrency",
        "Culinary",
        "Dating",
        "Design",
        "Digital Media",
        "Electronic Cigarettes",
        "Electronics",
        "Employment",
        "Entertainment",
        "Equipment",
        "Finance",
        "Food & Beverages",
        "Gaming",
        "Health & Fitness",
        "Hobbies",
        "Home",
        "Hospitality",
        "Information",
        "Jewelry",
        "Kitchenware",
        "Legal",
        "Lifestyle",
        "Medical",
        "Music",
        "News & Education",
        "Occasions & Gifts",
        "Office Supply",
        "Outdoors",
        "Parenting",
        "Personal Care",
        "Pet Care",
        "Quizzes",
        "Real Estate",
        "Religion & Spirituality",
        "Retail & Wholesale",
        "Romance",
        "Science",
        "SEO",
        "Social Media",
        "Sports",
        "Supplements",
        "Survival & Security",
        "Technology",
        "Tobacco Accessories",
        "Travel",
    ],
};

module.exports = function getData() {
    return data;
};
